apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: javierhn-sr3-16cards
  namespace: javierhn-restricted
spec:
  slotsPerWorker: 8
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          nodeSelector:
            brightcomputing.com/node-category: 'compute'
          serviceAccountName: javierhn
          volumes:
            - name: mydir
              hostPath:
                path: /home/javierhn/models/sr3_profiling
                type: Directory
            - name: scratch
              emptyDir: {}
            - name: ceph
              hostPath:
                path: /voyager/ceph/users/javierhn
                type: Directory
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.21.2/ubuntu22.04/habanalabs/pytorch-installer-2.6.0:latest
              name: sr3-launcher
              resources:
                requests:
                  cpu: 2
                  memory: 4Gi
                limits:
                  cpu: 4
                  memory: 8Gi
              volumeMounts:
                - name: mydir
                  mountPath: /mydir
                - name: scratch
                  mountPath: /scratch
                - name: ceph
                  mountPath: /ceph
              command: ["/bin/bash", "-c"]
              args:
                - >-
                  /usr/bin/ssh-keygen -A;
                  /usr/sbin/sshd;
                  NUM_NODES=2;
                  NGPU_PER_NODE=8;
                  N_CARDS=$((NUM_NODES*NGPU_PER_NODE));

                  declare -xr RUN_PATH=/mydir;
                  declare -xr MODEL_PATH=/mydir/Super-Resolution-SR3;
                  declare -xr PT_HPU_LAZY_MODE=1;
                  declare -xr PT_HPU_MAX_COMPOUND_OP_SIZE=40
                
                  HOSTSFILE=${HOSTSFILE:-$OMPI_MCA_orte_default_hostfile};
                  declare -xr MASTER_ADDR=$(head -n 1 $HOSTSFILE | sed -n s/[[:space:]]slots.*//p);
                  declare -xr MASTER_PORT=${MASTER_PORT:-15566};

                  echo $MASTER_ADDR;
                  echo $MASTER_PORT;

                  sleep 30s;

                  mpirun  --npernode 1 \
                    --tag-output \
                    --allow-run-as-root \
                    --prefix $MPI_ROOT \
                    -x MODEL_PATH \
                    $RUN_PATH/setup.sh;

                  CMD="python $MODEL_PATH/sr.py \
                       -p train \
                       --distributed \
                       -c $RUN_PATH/sr_sr3_64_256_set3_16cards.json";

                  mpirun -n $N_CARDS \
                    --bind-to core \
                    --map-by socket:PE=6 \
                    --rank-by core \
                    --report-bindings \
                    --allow-run-as-root \
                    -x PT_HPU_MAX_COMPOUND_OP_SIZE  \
                    -x PT_HPU_LAZY_MODE \
                    -x MASTER_ADDR=$MASTER_ADDR \
                    -x MASTER_PORT=$MASTER_PORT \
                    $CMD;
                  #sleep 500s;


    Worker:
      replicas: 2
      template:
        spec:
          serviceAccountName: javierhn
          tolerations:
            - key: "synapse"
              operator: "Equal"
              value: "1.21"
              effect: "NoSchedule"
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                 - matchExpressions:
                    - key: synapse
                      operator: In
                      values:
                      - "1.21"
                    - key: kubernetes.io/hostname
                      operator: NotIn
                      values:
                      - vgr-1-07
                      - vgr-1-10
          volumes:
            - name: mydir
              hostPath:
                path: /home/javierhn/models/sr3_profiling
                type: Directory
            - name: scratch
              emptyDir: {}
            - name: ceph 
              hostPath:
                path: /voyager/ceph/users/javierhn
                type: Directory
          hostIPC: true
          containers:
            - image: vault.habana.ai/gaudi-docker/1.21.2/ubuntu22.04/habanalabs/pytorch-installer-2.6.0:latest
              name: sr3-worker
              #imagePullPolicy: Always
              resources:
                limits:
                  habana.ai/gaudi: 8
                  cpu: 94
                  memory: 409Gi
                  hugepages-2Mi: 30000Mi
                requests:
                  habana.ai/gaudi: 8
                  cpu: 94
                  memory: 409Gi
                  hugepages-2Mi: 30000Mi
              volumeMounts:
                - name: mydir
                  mountPath: /mydir
                - name: scratch
                  mountPath: /scratch
                - name: ceph
                  mountPath: /ceph
              command: ["/bin/bash", "-c"]
              args:
                - >-
                   /usr/bin/ssh-keygen -A;
                   /usr/sbin/sshd;
                   sleep 365d;
 
