apiVersion: v1
kind: Pod
metadata:
  name: sr3-1card-pod-profiling-gaudi2
spec:
  restartPolicy: Never
  tolerations:
     - key: "synapse"
       operator: "Equal"
       value: "1.18"
       effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
         - matchExpressions:
           - key: synapse
             operator: In
             values:
              - "1.18"
           - key: kubernetes.io/hostname
             operator: In
             values:
              - vgr-1-07
              - vgr-1-10
  volumes:
    - name: scratch
      emptyDir: {}
    - name: mydir
      hostPath:
        path: /home/javierhn/models/sr3_profiling
        type: Directory
    - name: ceph
      hostPath:
        path: /voyager/ceph/users/javierhn
        type: Directory
  hostIPC: true
  containers:
    - name: gaudi-container
      image: vault.habana.ai/gaudi-docker/1.18.0/ubuntu22.04/habanalabs/pytorch-installer-2.4.0:latest
      volumeMounts:
        - mountPath: /scratch
          name: scratch
        - mountPath: /mydir
          name: mydir 
        - mountPath: /ceph
          name: ceph 
      resources:
        limits:
          memory: 16G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 30000Mi
        requests:
          memory: 16G
          cpu: 12
          habana.ai/gaudi: 1
          hugepages-2Mi: 30000Mi
      command: ["/bin/sh","-c"]
      args:
        - >-
           hl-smi;
           export HOME=/scratch/tmp;
           export PATH=/scratch/tmp/.local/bin:$PATH;
           export MODEL_PATH=/mydir/Super-Resolution-SR3;
           export XXXXXXXPT_HPU_MAX_COMPOUND_OP_SIZE=40;
           cd /mydir;
           pip install -r $MODEL_PATH/requirements.txt;

           python $MODEL_PATH/sr.py \
                    -p train \
                    -c /mydir/sr_sr3_64_256_set3_1card.json;
         

